import './globals.css';
import Sidebar from '../components/sidebar';
import ToastCont from '@/components/toast_cont';
import Head from 'next/head';
import { usePathname } from 'next/navigation';
import Navbar from '@/components/navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en" className='text-black bg-gray-200 dark:text-white dark:bg-[#111010]'>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body className="antialiased mb-40  mx-4 lg:mx-auto">
        <ToastCont />
        <Navbar />
        {/* <Sidebar /> */}
        <main className="flex-auto min-w-0 mt-6 md:mt-0 flex flex-col px-2 md:px-0">
          {children}
        </main>
      </body>
    </html>
  )
}